theme: jekyll-theme-cayman
lang: ja-JP
title: 情報数理学部
description: 情報と数理の力で、人が主役のAI社会を創る。
logo: assets/images/MI_logo.png
collections:
  faculty_members:
    output: true
github:
  is_project_page: false
